# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("SearchSortAlgos"); Pkg.test("SearchSortAlgos"; coverage=true)'

after_success:
  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("SearchSortAlgos")); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("SearchSortAlgos")); using Coverage; Coveralls.submit(process_folder())'
